name: smart_plant_app
description: "Smart Plant App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.15.1
  firebase_database: ^10.2.5
  firebase_messaging: ^14.6.7
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  http: ^1.1.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
