// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJz_4qcVLvqZ85qIgJ5fezpD5QeupDswM',
    appId: '1:404485323568:web:6cf528e7a6b10ce501e6f5',
    messagingSenderId: '404485323568',
    projectId: 'smart-plant-app-1',
    authDomain: 'smart-plant-app-1.firebaseapp.com',
    databaseURL: 'https://smart-plant-app-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-plant-app-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTWwpwvNwUa6hEmN4nKVDwdpAWDKOWVpc',
    appId: '1:404485323568:android:2b29f554c4b7d5d701e6f5',
    messagingSenderId: '404485323568',
    projectId: 'smart-plant-app-1',
    databaseURL: 'https://smart-plant-app-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-plant-app-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL3qQu0qYVxPv3GPG7iVn8fLk7Ok-4rRI',
    appId: '1:404485323568:ios:c09324e3ec46ff5801e6f5',
    messagingSenderId: '404485323568',
    projectId: 'smart-plant-app-1',
    databaseURL: 'https://smart-plant-app-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-plant-app-1.firebasestorage.app',
    iosBundleId: 'com.matter.plant.smartPlantApp',
  );

}